/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// DocumentsAPIService DocumentsAPI service
type DocumentsAPIService service

type ApiDocumentServiceInsertDocumentRequest struct {
	ctx context.Context
	ApiService *DocumentsAPIService
	insertDocumentRequest *InsertDocumentRequest
}

func (r ApiDocumentServiceInsertDocumentRequest) InsertDocumentRequest(insertDocumentRequest InsertDocumentRequest) ApiDocumentServiceInsertDocumentRequest {
	r.insertDocumentRequest = &insertDocumentRequest
	return r
}

func (r ApiDocumentServiceInsertDocumentRequest) Execute() (*http.Response, error) {
	return r.ApiService.DocumentServiceInsertDocumentExecute(r)
}

/*
DocumentServiceInsertDocument Method for DocumentServiceInsertDocument

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiDocumentServiceInsertDocumentRequest
*/
func (a *DocumentsAPIService) DocumentServiceInsertDocument(ctx context.Context) ApiDocumentServiceInsertDocumentRequest {
	return ApiDocumentServiceInsertDocumentRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *DocumentsAPIService) DocumentServiceInsertDocumentExecute(r ApiDocumentServiceInsertDocumentRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DocumentsAPIService.DocumentServiceInsertDocument")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/insert-document"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.insertDocumentRequest == nil {
		return nil, reportError("insertDocumentRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.insertDocumentRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
