/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InsertDocumentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InsertDocumentRequest{}

// InsertDocumentRequest struct for InsertDocumentRequest
type InsertDocumentRequest struct {
	Type string `json:"type"`
	Source string `json:"source"`
}

type _InsertDocumentRequest InsertDocumentRequest

// NewInsertDocumentRequest instantiates a new InsertDocumentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInsertDocumentRequest(type_ string, source string) *InsertDocumentRequest {
	this := InsertDocumentRequest{}
	this.Type = type_
	this.Source = source
	return &this
}

// NewInsertDocumentRequestWithDefaults instantiates a new InsertDocumentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInsertDocumentRequestWithDefaults() *InsertDocumentRequest {
	this := InsertDocumentRequest{}
	return &this
}

// GetType returns the Type field value
func (o *InsertDocumentRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *InsertDocumentRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *InsertDocumentRequest) SetType(v string) {
	o.Type = v
}

// GetSource returns the Source field value
func (o *InsertDocumentRequest) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *InsertDocumentRequest) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *InsertDocumentRequest) SetSource(v string) {
	o.Source = v
}

func (o InsertDocumentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InsertDocumentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *InsertDocumentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInsertDocumentRequest := _InsertDocumentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInsertDocumentRequest)

	if err != nil {
		return err
	}

	*o = InsertDocumentRequest(varInsertDocumentRequest)

	return err
}

type NullableInsertDocumentRequest struct {
	value *InsertDocumentRequest
	isSet bool
}

func (v NullableInsertDocumentRequest) Get() *InsertDocumentRequest {
	return v.value
}

func (v *NullableInsertDocumentRequest) Set(val *InsertDocumentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInsertDocumentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInsertDocumentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInsertDocumentRequest(val *InsertDocumentRequest) *NullableInsertDocumentRequest {
	return &NullableInsertDocumentRequest{value: val, isSet: true}
}

func (v NullableInsertDocumentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInsertDocumentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


