/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNoteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNoteRequest{}

// CreateNoteRequest struct for CreateNoteRequest
type CreateNoteRequest struct {
	Body string `json:"body"`
	Type NoteType `json:"type"`
}

type _CreateNoteRequest CreateNoteRequest

// NewCreateNoteRequest instantiates a new CreateNoteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNoteRequest(body string, type_ NoteType) *CreateNoteRequest {
	this := CreateNoteRequest{}
	this.Body = body
	this.Type = type_
	return &this
}

// NewCreateNoteRequestWithDefaults instantiates a new CreateNoteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNoteRequestWithDefaults() *CreateNoteRequest {
	this := CreateNoteRequest{}
	return &this
}

// GetBody returns the Body field value
func (o *CreateNoteRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *CreateNoteRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *CreateNoteRequest) SetBody(v string) {
	o.Body = v
}

// GetType returns the Type field value
func (o *CreateNoteRequest) GetType() NoteType {
	if o == nil {
		var ret NoteType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateNoteRequest) GetTypeOk() (*NoteType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateNoteRequest) SetType(v NoteType) {
	o.Type = v
}

func (o CreateNoteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNoteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["body"] = o.Body
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CreateNoteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"body",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNoteRequest := _CreateNoteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNoteRequest)

	if err != nil {
		return err
	}

	*o = CreateNoteRequest(varCreateNoteRequest)

	return err
}

type NullableCreateNoteRequest struct {
	value *CreateNoteRequest
	isSet bool
}

func (v NullableCreateNoteRequest) Get() *CreateNoteRequest {
	return v.value
}

func (v *NullableCreateNoteRequest) Set(val *CreateNoteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNoteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNoteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNoteRequest(val *CreateNoteRequest) *NullableCreateNoteRequest {
	return &NullableCreateNoteRequest{value: val, isSet: true}
}

func (v NullableCreateNoteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNoteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


