/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetBookmarksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBookmarksResponse{}

// GetBookmarksResponse struct for GetBookmarksResponse
type GetBookmarksResponse struct {
	Bookmarks []Bookmark `json:"bookmarks"`
}

type _GetBookmarksResponse GetBookmarksResponse

// NewGetBookmarksResponse instantiates a new GetBookmarksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBookmarksResponse(bookmarks []Bookmark) *GetBookmarksResponse {
	this := GetBookmarksResponse{}
	this.Bookmarks = bookmarks
	return &this
}

// NewGetBookmarksResponseWithDefaults instantiates a new GetBookmarksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBookmarksResponseWithDefaults() *GetBookmarksResponse {
	this := GetBookmarksResponse{}
	return &this
}

// GetBookmarks returns the Bookmarks field value
func (o *GetBookmarksResponse) GetBookmarks() []Bookmark {
	if o == nil {
		var ret []Bookmark
		return ret
	}

	return o.Bookmarks
}

// GetBookmarksOk returns a tuple with the Bookmarks field value
// and a boolean to check if the value has been set.
func (o *GetBookmarksResponse) GetBookmarksOk() ([]Bookmark, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bookmarks, true
}

// SetBookmarks sets field value
func (o *GetBookmarksResponse) SetBookmarks(v []Bookmark) {
	o.Bookmarks = v
}

func (o GetBookmarksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBookmarksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bookmarks"] = o.Bookmarks
	return toSerialize, nil
}

func (o *GetBookmarksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bookmarks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetBookmarksResponse := _GetBookmarksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetBookmarksResponse)

	if err != nil {
		return err
	}

	*o = GetBookmarksResponse(varGetBookmarksResponse)

	return err
}

type NullableGetBookmarksResponse struct {
	value *GetBookmarksResponse
	isSet bool
}

func (v NullableGetBookmarksResponse) Get() *GetBookmarksResponse {
	return v.value
}

func (v *NullableGetBookmarksResponse) Set(val *GetBookmarksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBookmarksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBookmarksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBookmarksResponse(val *GetBookmarksResponse) *NullableGetBookmarksResponse {
	return &NullableGetBookmarksResponse{value: val, isSet: true}
}

func (v NullableGetBookmarksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBookmarksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


