/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
)

// checks if the OpenGraphMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenGraphMetadata{}

// OpenGraphMetadata struct for OpenGraphMetadata
type OpenGraphMetadata struct {
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Image *string `json:"image,omitempty"`
	Url *string `json:"url,omitempty"`
	SiteName *string `json:"siteName,omitempty"`
	Type *string `json:"type,omitempty"`
	Locale *string `json:"locale,omitempty"`
	ArticleAuthor *string `json:"articleAuthor,omitempty"`
	ArticlePublishedTime *string `json:"articlePublishedTime,omitempty"`
	ArticleModifiedTime *string `json:"articleModifiedTime,omitempty"`
	ArticleSection *string `json:"articleSection,omitempty"`
	ArticleTag []string `json:"articleTag,omitempty"`
}

// NewOpenGraphMetadata instantiates a new OpenGraphMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenGraphMetadata() *OpenGraphMetadata {
	this := OpenGraphMetadata{}
	return &this
}

// NewOpenGraphMetadataWithDefaults instantiates a new OpenGraphMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenGraphMetadataWithDefaults() *OpenGraphMetadata {
	this := OpenGraphMetadata{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *OpenGraphMetadata) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OpenGraphMetadata) SetDescription(v string) {
	o.Description = &v
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *OpenGraphMetadata) SetImage(v string) {
	o.Image = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *OpenGraphMetadata) SetUrl(v string) {
	o.Url = &v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetSiteName() string {
	if o == nil || IsNil(o.SiteName) {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetSiteNameOk() (*string, bool) {
	if o == nil || IsNil(o.SiteName) {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasSiteName() bool {
	if o != nil && !IsNil(o.SiteName) {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *OpenGraphMetadata) SetSiteName(v string) {
	o.SiteName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *OpenGraphMetadata) SetType(v string) {
	o.Type = &v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetLocale() string {
	if o == nil || IsNil(o.Locale) {
		var ret string
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetLocaleOk() (*string, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given string and assigns it to the Locale field.
func (o *OpenGraphMetadata) SetLocale(v string) {
	o.Locale = &v
}

// GetArticleAuthor returns the ArticleAuthor field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetArticleAuthor() string {
	if o == nil || IsNil(o.ArticleAuthor) {
		var ret string
		return ret
	}
	return *o.ArticleAuthor
}

// GetArticleAuthorOk returns a tuple with the ArticleAuthor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetArticleAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.ArticleAuthor) {
		return nil, false
	}
	return o.ArticleAuthor, true
}

// HasArticleAuthor returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasArticleAuthor() bool {
	if o != nil && !IsNil(o.ArticleAuthor) {
		return true
	}

	return false
}

// SetArticleAuthor gets a reference to the given string and assigns it to the ArticleAuthor field.
func (o *OpenGraphMetadata) SetArticleAuthor(v string) {
	o.ArticleAuthor = &v
}

// GetArticlePublishedTime returns the ArticlePublishedTime field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetArticlePublishedTime() string {
	if o == nil || IsNil(o.ArticlePublishedTime) {
		var ret string
		return ret
	}
	return *o.ArticlePublishedTime
}

// GetArticlePublishedTimeOk returns a tuple with the ArticlePublishedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetArticlePublishedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ArticlePublishedTime) {
		return nil, false
	}
	return o.ArticlePublishedTime, true
}

// HasArticlePublishedTime returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasArticlePublishedTime() bool {
	if o != nil && !IsNil(o.ArticlePublishedTime) {
		return true
	}

	return false
}

// SetArticlePublishedTime gets a reference to the given string and assigns it to the ArticlePublishedTime field.
func (o *OpenGraphMetadata) SetArticlePublishedTime(v string) {
	o.ArticlePublishedTime = &v
}

// GetArticleModifiedTime returns the ArticleModifiedTime field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetArticleModifiedTime() string {
	if o == nil || IsNil(o.ArticleModifiedTime) {
		var ret string
		return ret
	}
	return *o.ArticleModifiedTime
}

// GetArticleModifiedTimeOk returns a tuple with the ArticleModifiedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetArticleModifiedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.ArticleModifiedTime) {
		return nil, false
	}
	return o.ArticleModifiedTime, true
}

// HasArticleModifiedTime returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasArticleModifiedTime() bool {
	if o != nil && !IsNil(o.ArticleModifiedTime) {
		return true
	}

	return false
}

// SetArticleModifiedTime gets a reference to the given string and assigns it to the ArticleModifiedTime field.
func (o *OpenGraphMetadata) SetArticleModifiedTime(v string) {
	o.ArticleModifiedTime = &v
}

// GetArticleSection returns the ArticleSection field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetArticleSection() string {
	if o == nil || IsNil(o.ArticleSection) {
		var ret string
		return ret
	}
	return *o.ArticleSection
}

// GetArticleSectionOk returns a tuple with the ArticleSection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetArticleSectionOk() (*string, bool) {
	if o == nil || IsNil(o.ArticleSection) {
		return nil, false
	}
	return o.ArticleSection, true
}

// HasArticleSection returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasArticleSection() bool {
	if o != nil && !IsNil(o.ArticleSection) {
		return true
	}

	return false
}

// SetArticleSection gets a reference to the given string and assigns it to the ArticleSection field.
func (o *OpenGraphMetadata) SetArticleSection(v string) {
	o.ArticleSection = &v
}

// GetArticleTag returns the ArticleTag field value if set, zero value otherwise.
func (o *OpenGraphMetadata) GetArticleTag() []string {
	if o == nil || IsNil(o.ArticleTag) {
		var ret []string
		return ret
	}
	return o.ArticleTag
}

// GetArticleTagOk returns a tuple with the ArticleTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenGraphMetadata) GetArticleTagOk() ([]string, bool) {
	if o == nil || IsNil(o.ArticleTag) {
		return nil, false
	}
	return o.ArticleTag, true
}

// HasArticleTag returns a boolean if a field has been set.
func (o *OpenGraphMetadata) HasArticleTag() bool {
	if o != nil && !IsNil(o.ArticleTag) {
		return true
	}

	return false
}

// SetArticleTag gets a reference to the given []string and assigns it to the ArticleTag field.
func (o *OpenGraphMetadata) SetArticleTag(v []string) {
	o.ArticleTag = v
}

func (o OpenGraphMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenGraphMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.SiteName) {
		toSerialize["siteName"] = o.SiteName
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.ArticleAuthor) {
		toSerialize["articleAuthor"] = o.ArticleAuthor
	}
	if !IsNil(o.ArticlePublishedTime) {
		toSerialize["articlePublishedTime"] = o.ArticlePublishedTime
	}
	if !IsNil(o.ArticleModifiedTime) {
		toSerialize["articleModifiedTime"] = o.ArticleModifiedTime
	}
	if !IsNil(o.ArticleSection) {
		toSerialize["articleSection"] = o.ArticleSection
	}
	if !IsNil(o.ArticleTag) {
		toSerialize["articleTag"] = o.ArticleTag
	}
	return toSerialize, nil
}

type NullableOpenGraphMetadata struct {
	value *OpenGraphMetadata
	isSet bool
}

func (v NullableOpenGraphMetadata) Get() *OpenGraphMetadata {
	return v.value
}

func (v *NullableOpenGraphMetadata) Set(val *OpenGraphMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenGraphMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenGraphMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenGraphMetadata(val *OpenGraphMetadata) *NullableOpenGraphMetadata {
	return &NullableOpenGraphMetadata{value: val, isSet: true}
}

func (v NullableOpenGraphMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenGraphMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


