/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NoteSection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoteSection{}

// NoteSection struct for NoteSection
type NoteSection struct {
	Type NoteSectionType `json:"type"`
	Content map[string]string `json:"content"`
}

type _NoteSection NoteSection

// NewNoteSection instantiates a new NoteSection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoteSection(type_ NoteSectionType, content map[string]string) *NoteSection {
	this := NoteSection{}
	this.Type = type_
	this.Content = content
	return &this
}

// NewNoteSectionWithDefaults instantiates a new NoteSection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoteSectionWithDefaults() *NoteSection {
	this := NoteSection{}
	return &this
}

// GetType returns the Type field value
func (o *NoteSection) GetType() NoteSectionType {
	if o == nil {
		var ret NoteSectionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *NoteSection) GetTypeOk() (*NoteSectionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *NoteSection) SetType(v NoteSectionType) {
	o.Type = v
}

// GetContent returns the Content field value
func (o *NoteSection) GetContent() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *NoteSection) GetContentOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *NoteSection) SetContent(v map[string]string) {
	o.Content = v
}

func (o NoteSection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoteSection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *NoteSection) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNoteSection := _NoteSection{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNoteSection)

	if err != nil {
		return err
	}

	*o = NoteSection(varNoteSection)

	return err
}

type NullableNoteSection struct {
	value *NoteSection
	isSet bool
}

func (v NullableNoteSection) Get() *NoteSection {
	return v.value
}

func (v *NullableNoteSection) Set(val *NoteSection) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteSection) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteSection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteSection(val *NoteSection) *NullableNoteSection {
	return &NullableNoteSection{value: val, isSet: true}
}

func (v NullableNoteSection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteSection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


