/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Bookmark type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Bookmark{}

// Bookmark struct for Bookmark
type Bookmark struct {
	Id string `json:"id"`
	SourceUrl string `json:"sourceUrl"`
	CollectionId *string `json:"collectionId,omitempty"`
	Title *string `json:"title,omitempty"`
	IsArchived *bool `json:"isArchived,omitempty"`
	IsFavorite *bool `json:"isFavorite,omitempty"`
	CosmicImages []BookmarkImage `json:"cosmicImages,omitempty"`
	CosmicLinks []BookmarkLink `json:"cosmicLinks,omitempty"`
	CosmicSummary *string `json:"cosmicSummary,omitempty"`
	CosmicTags []string `json:"cosmicTags,omitempty"`
	Metadata *BookmarkMetadata `json:"metadata,omitempty"`
	UserId string `json:"userId"`
}

type _Bookmark Bookmark

// NewBookmark instantiates a new Bookmark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmark(id string, sourceUrl string, userId string) *Bookmark {
	this := Bookmark{}
	this.Id = id
	this.SourceUrl = sourceUrl
	this.UserId = userId
	return &this
}

// NewBookmarkWithDefaults instantiates a new Bookmark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarkWithDefaults() *Bookmark {
	this := Bookmark{}
	return &this
}

// GetId returns the Id field value
func (o *Bookmark) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Bookmark) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Bookmark) SetId(v string) {
	o.Id = v
}

// GetSourceUrl returns the SourceUrl field value
func (o *Bookmark) GetSourceUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceUrl
}

// GetSourceUrlOk returns a tuple with the SourceUrl field value
// and a boolean to check if the value has been set.
func (o *Bookmark) GetSourceUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceUrl, true
}

// SetSourceUrl sets field value
func (o *Bookmark) SetSourceUrl(v string) {
	o.SourceUrl = v
}

// GetCollectionId returns the CollectionId field value if set, zero value otherwise.
func (o *Bookmark) GetCollectionId() string {
	if o == nil || IsNil(o.CollectionId) {
		var ret string
		return ret
	}
	return *o.CollectionId
}

// GetCollectionIdOk returns a tuple with the CollectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCollectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CollectionId) {
		return nil, false
	}
	return o.CollectionId, true
}

// HasCollectionId returns a boolean if a field has been set.
func (o *Bookmark) HasCollectionId() bool {
	if o != nil && !IsNil(o.CollectionId) {
		return true
	}

	return false
}

// SetCollectionId gets a reference to the given string and assigns it to the CollectionId field.
func (o *Bookmark) SetCollectionId(v string) {
	o.CollectionId = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Bookmark) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Bookmark) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Bookmark) SetTitle(v string) {
	o.Title = &v
}

// GetIsArchived returns the IsArchived field value if set, zero value otherwise.
func (o *Bookmark) GetIsArchived() bool {
	if o == nil || IsNil(o.IsArchived) {
		var ret bool
		return ret
	}
	return *o.IsArchived
}

// GetIsArchivedOk returns a tuple with the IsArchived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetIsArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsArchived) {
		return nil, false
	}
	return o.IsArchived, true
}

// HasIsArchived returns a boolean if a field has been set.
func (o *Bookmark) HasIsArchived() bool {
	if o != nil && !IsNil(o.IsArchived) {
		return true
	}

	return false
}

// SetIsArchived gets a reference to the given bool and assigns it to the IsArchived field.
func (o *Bookmark) SetIsArchived(v bool) {
	o.IsArchived = &v
}

// GetIsFavorite returns the IsFavorite field value if set, zero value otherwise.
func (o *Bookmark) GetIsFavorite() bool {
	if o == nil || IsNil(o.IsFavorite) {
		var ret bool
		return ret
	}
	return *o.IsFavorite
}

// GetIsFavoriteOk returns a tuple with the IsFavorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetIsFavoriteOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFavorite) {
		return nil, false
	}
	return o.IsFavorite, true
}

// HasIsFavorite returns a boolean if a field has been set.
func (o *Bookmark) HasIsFavorite() bool {
	if o != nil && !IsNil(o.IsFavorite) {
		return true
	}

	return false
}

// SetIsFavorite gets a reference to the given bool and assigns it to the IsFavorite field.
func (o *Bookmark) SetIsFavorite(v bool) {
	o.IsFavorite = &v
}

// GetCosmicImages returns the CosmicImages field value if set, zero value otherwise.
func (o *Bookmark) GetCosmicImages() []BookmarkImage {
	if o == nil || IsNil(o.CosmicImages) {
		var ret []BookmarkImage
		return ret
	}
	return o.CosmicImages
}

// GetCosmicImagesOk returns a tuple with the CosmicImages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCosmicImagesOk() ([]BookmarkImage, bool) {
	if o == nil || IsNil(o.CosmicImages) {
		return nil, false
	}
	return o.CosmicImages, true
}

// HasCosmicImages returns a boolean if a field has been set.
func (o *Bookmark) HasCosmicImages() bool {
	if o != nil && !IsNil(o.CosmicImages) {
		return true
	}

	return false
}

// SetCosmicImages gets a reference to the given []BookmarkImage and assigns it to the CosmicImages field.
func (o *Bookmark) SetCosmicImages(v []BookmarkImage) {
	o.CosmicImages = v
}

// GetCosmicLinks returns the CosmicLinks field value if set, zero value otherwise.
func (o *Bookmark) GetCosmicLinks() []BookmarkLink {
	if o == nil || IsNil(o.CosmicLinks) {
		var ret []BookmarkLink
		return ret
	}
	return o.CosmicLinks
}

// GetCosmicLinksOk returns a tuple with the CosmicLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCosmicLinksOk() ([]BookmarkLink, bool) {
	if o == nil || IsNil(o.CosmicLinks) {
		return nil, false
	}
	return o.CosmicLinks, true
}

// HasCosmicLinks returns a boolean if a field has been set.
func (o *Bookmark) HasCosmicLinks() bool {
	if o != nil && !IsNil(o.CosmicLinks) {
		return true
	}

	return false
}

// SetCosmicLinks gets a reference to the given []BookmarkLink and assigns it to the CosmicLinks field.
func (o *Bookmark) SetCosmicLinks(v []BookmarkLink) {
	o.CosmicLinks = v
}

// GetCosmicSummary returns the CosmicSummary field value if set, zero value otherwise.
func (o *Bookmark) GetCosmicSummary() string {
	if o == nil || IsNil(o.CosmicSummary) {
		var ret string
		return ret
	}
	return *o.CosmicSummary
}

// GetCosmicSummaryOk returns a tuple with the CosmicSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCosmicSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.CosmicSummary) {
		return nil, false
	}
	return o.CosmicSummary, true
}

// HasCosmicSummary returns a boolean if a field has been set.
func (o *Bookmark) HasCosmicSummary() bool {
	if o != nil && !IsNil(o.CosmicSummary) {
		return true
	}

	return false
}

// SetCosmicSummary gets a reference to the given string and assigns it to the CosmicSummary field.
func (o *Bookmark) SetCosmicSummary(v string) {
	o.CosmicSummary = &v
}

// GetCosmicTags returns the CosmicTags field value if set, zero value otherwise.
func (o *Bookmark) GetCosmicTags() []string {
	if o == nil || IsNil(o.CosmicTags) {
		var ret []string
		return ret
	}
	return o.CosmicTags
}

// GetCosmicTagsOk returns a tuple with the CosmicTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetCosmicTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.CosmicTags) {
		return nil, false
	}
	return o.CosmicTags, true
}

// HasCosmicTags returns a boolean if a field has been set.
func (o *Bookmark) HasCosmicTags() bool {
	if o != nil && !IsNil(o.CosmicTags) {
		return true
	}

	return false
}

// SetCosmicTags gets a reference to the given []string and assigns it to the CosmicTags field.
func (o *Bookmark) SetCosmicTags(v []string) {
	o.CosmicTags = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Bookmark) GetMetadata() BookmarkMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret BookmarkMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Bookmark) GetMetadataOk() (*BookmarkMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Bookmark) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given BookmarkMetadata and assigns it to the Metadata field.
func (o *Bookmark) SetMetadata(v BookmarkMetadata) {
	o.Metadata = &v
}

// GetUserId returns the UserId field value
func (o *Bookmark) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *Bookmark) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *Bookmark) SetUserId(v string) {
	o.UserId = v
}

func (o Bookmark) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Bookmark) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["sourceUrl"] = o.SourceUrl
	if !IsNil(o.CollectionId) {
		toSerialize["collectionId"] = o.CollectionId
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.IsArchived) {
		toSerialize["isArchived"] = o.IsArchived
	}
	if !IsNil(o.IsFavorite) {
		toSerialize["isFavorite"] = o.IsFavorite
	}
	if !IsNil(o.CosmicImages) {
		toSerialize["cosmicImages"] = o.CosmicImages
	}
	if !IsNil(o.CosmicLinks) {
		toSerialize["cosmicLinks"] = o.CosmicLinks
	}
	if !IsNil(o.CosmicSummary) {
		toSerialize["cosmicSummary"] = o.CosmicSummary
	}
	if !IsNil(o.CosmicTags) {
		toSerialize["cosmicTags"] = o.CosmicTags
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *Bookmark) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"sourceUrl",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmark := _Bookmark{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmark)

	if err != nil {
		return err
	}

	*o = Bookmark(varBookmark)

	return err
}

type NullableBookmark struct {
	value *Bookmark
	isSet bool
}

func (v NullableBookmark) Get() *Bookmark {
	return v.value
}

func (v *NullableBookmark) Set(val *Bookmark) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmark) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmark(val *Bookmark) *NullableBookmark {
	return &NullableBookmark{value: val, isSet: true}
}

func (v NullableBookmark) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmark) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


