/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchBookmarksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchBookmarksResponse{}

// SearchBookmarksResponse struct for SearchBookmarksResponse
type SearchBookmarksResponse struct {
	Bookmarks []Bookmark `json:"bookmarks"`
	Total *int32 `json:"total,omitempty"`
}

type _SearchBookmarksResponse SearchBookmarksResponse

// NewSearchBookmarksResponse instantiates a new SearchBookmarksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchBookmarksResponse(bookmarks []Bookmark) *SearchBookmarksResponse {
	this := SearchBookmarksResponse{}
	this.Bookmarks = bookmarks
	return &this
}

// NewSearchBookmarksResponseWithDefaults instantiates a new SearchBookmarksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchBookmarksResponseWithDefaults() *SearchBookmarksResponse {
	this := SearchBookmarksResponse{}
	return &this
}

// GetBookmarks returns the Bookmarks field value
func (o *SearchBookmarksResponse) GetBookmarks() []Bookmark {
	if o == nil {
		var ret []Bookmark
		return ret
	}

	return o.Bookmarks
}

// GetBookmarksOk returns a tuple with the Bookmarks field value
// and a boolean to check if the value has been set.
func (o *SearchBookmarksResponse) GetBookmarksOk() ([]Bookmark, bool) {
	if o == nil {
		return nil, false
	}
	return o.Bookmarks, true
}

// SetBookmarks sets field value
func (o *SearchBookmarksResponse) SetBookmarks(v []Bookmark) {
	o.Bookmarks = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *SearchBookmarksResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchBookmarksResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *SearchBookmarksResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *SearchBookmarksResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o SearchBookmarksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchBookmarksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bookmarks"] = o.Bookmarks
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

func (o *SearchBookmarksResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bookmarks",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchBookmarksResponse := _SearchBookmarksResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchBookmarksResponse)

	if err != nil {
		return err
	}

	*o = SearchBookmarksResponse(varSearchBookmarksResponse)

	return err
}

type NullableSearchBookmarksResponse struct {
	value *SearchBookmarksResponse
	isSet bool
}

func (v NullableSearchBookmarksResponse) Get() *SearchBookmarksResponse {
	return v.value
}

func (v *NullableSearchBookmarksResponse) Set(val *SearchBookmarksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchBookmarksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchBookmarksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchBookmarksResponse(val *SearchBookmarksResponse) *NullableSearchBookmarksResponse {
	return &NullableSearchBookmarksResponse{value: val, isSet: true}
}

func (v NullableSearchBookmarksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchBookmarksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


