/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebSocketMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebSocketMessage{}

// WebSocketMessage struct for WebSocketMessage
type WebSocketMessage struct {
	Event string `json:"event"`
	Data WebSocketMessageData `json:"data"`
}

type _WebSocketMessage WebSocketMessage

// NewWebSocketMessage instantiates a new WebSocketMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebSocketMessage(event string, data WebSocketMessageData) *WebSocketMessage {
	this := WebSocketMessage{}
	this.Event = event
	this.Data = data
	return &this
}

// NewWebSocketMessageWithDefaults instantiates a new WebSocketMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebSocketMessageWithDefaults() *WebSocketMessage {
	this := WebSocketMessage{}
	return &this
}

// GetEvent returns the Event field value
func (o *WebSocketMessage) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *WebSocketMessage) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *WebSocketMessage) SetEvent(v string) {
	o.Event = v
}

// GetData returns the Data field value
func (o *WebSocketMessage) GetData() WebSocketMessageData {
	if o == nil {
		var ret WebSocketMessageData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebSocketMessage) GetDataOk() (*WebSocketMessageData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *WebSocketMessage) SetData(v WebSocketMessageData) {
	o.Data = v
}

func (o WebSocketMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebSocketMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event"] = o.Event
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *WebSocketMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebSocketMessage := _WebSocketMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebSocketMessage)

	if err != nil {
		return err
	}

	*o = WebSocketMessage(varWebSocketMessage)

	return err
}

type NullableWebSocketMessage struct {
	value *WebSocketMessage
	isSet bool
}

func (v NullableWebSocketMessage) Get() *WebSocketMessage {
	return v.value
}

func (v *NullableWebSocketMessage) Set(val *WebSocketMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableWebSocketMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableWebSocketMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebSocketMessage(val *WebSocketMessage) *NullableWebSocketMessage {
	return &NullableWebSocketMessage{value: val, isSet: true}
}

func (v NullableWebSocketMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebSocketMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


