/*
Cosmic Dolphin

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cosmicdolphinapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BookmarkError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BookmarkError{}

// BookmarkError struct for BookmarkError
type BookmarkError struct {
	Error string `json:"error"`
}

type _BookmarkError BookmarkError

// NewBookmarkError instantiates a new BookmarkError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBookmarkError(error_ string) *BookmarkError {
	this := BookmarkError{}
	this.Error = error_
	return &this
}

// NewBookmarkErrorWithDefaults instantiates a new BookmarkError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBookmarkErrorWithDefaults() *BookmarkError {
	this := BookmarkError{}
	return &this
}

// GetError returns the Error field value
func (o *BookmarkError) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *BookmarkError) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *BookmarkError) SetError(v string) {
	o.Error = v
}

func (o BookmarkError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BookmarkError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *BookmarkError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBookmarkError := _BookmarkError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBookmarkError)

	if err != nil {
		return err
	}

	*o = BookmarkError(varBookmarkError)

	return err
}

type NullableBookmarkError struct {
	value *BookmarkError
	isSet bool
}

func (v NullableBookmarkError) Get() *BookmarkError {
	return v.value
}

func (v *NullableBookmarkError) Set(val *BookmarkError) {
	v.value = val
	v.isSet = true
}

func (v NullableBookmarkError) IsSet() bool {
	return v.isSet
}

func (v *NullableBookmarkError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBookmarkError(val *BookmarkError) *NullableBookmarkError {
	return &NullableBookmarkError{value: val, isSet: true}
}

func (v NullableBookmarkError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBookmarkError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


